# Generated by Django 5.2.8 on 2026-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe_promotion',
            field=models.BooleanField(default=False, verbose_name='Подписка на акции'),
        ),
    ]
