# Generated by Django 5.2.8 on 2026-01-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_subscribe_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscribe_promotion',
            new_name='subscribe_promotions',
        ),
    ]
