# Generated by Django 5.2.8 on 2026-01-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patient_options_remove_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
