# Generated by Django 5.2.8 on 2025-11-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smallcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
