# Generated by Django 5.2.8 on 2025-11-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_smallcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcard',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='smallcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='smallcard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='squarecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='square_cards/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='squarecard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='squarecard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
