# Generated by Django 5.2.8 on 2025-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_smallcard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarecard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
