# Generated by Django 5.2.8 on 2025-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Свободно'), ('booked', 'Занято'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='available', max_length=20),
        ),
    ]
