# Generated by Django 5.2.8 on 2025-12-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_available',
        ),
    ]
