# Generated by Django 5.2.8 on 2025-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_schedule_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Свободно'), ('booked', 'Занято'), ('confirmed', 'Подтверждено'), ('completed', 'Приём состоялся'), ('cancelled', 'Отменено')], default='available', max_length=20),
        ),
    ]
