# Generated by Django 5.2.8 on 2025-12-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/', verbose_name='Медицинское заключение (PDF)'),
        ),
    ]
