# Generated by Django 5.2.8 on 2025-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='herocard',
            options={'verbose_name': 'Главная карточка'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='smallcard',
            options={'verbose_name_plural': 'Маленькие карточки'},
        ),
        migrations.AlterModelOptions(
            name='squarecard',
            options={'verbose_name_plural': 'Квадратные карточки'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_active',
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Баннер акции'),
        ),
    ]
