# Generated by Django 5.2.8 on 2026-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schedule_medical_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Свободно'), ('booked', 'Занято'), ('confirmed', 'Подтверждено'), ('completed', 'Приём состоялся'), ('cancelled', 'Отменено'), ('closed', 'Закрыто')], default='available', max_length=20),
        ),
    ]
