# Generated by Django 5.2.8 on 2026-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
