# Generated by Django 5.2.8 on 2026-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_review_options_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='Жалобы пациента')),
                ('ai_result', models.TextField(verbose_name='Анализ ИИ')),
                ('recommended_doctor', models.CharField(blank=True, max_length=100, verbose_name='Рекомендованный врач')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса')),
            ],
            options={
                'verbose_name': 'Анализ симптомов',
                'verbose_name_plural': 'История анализов ИИ',
                'ordering': ['-created_at'],
            },
        ),
    ]
